Cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = "Cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

Orders/urls.py
from django.urls import path
from .views import *

app_name = "Orders"

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="create"),
    path("GetRates/", GetShippingRates, name="GetRates"),
    path("Update_price/", UpdateTotalPrice, name="update_price")
]

Products/urls.py
from django.urls import path, include
from .views import *


app_name = 'Product'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_listview'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detailview'),
    path('ajax/', include('Products.ajaxurls')),
    path('land/<str:vland>', ProductListByLand, name="land"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login.urls', namespace='Account')),
    path('', include('StaticPages.urls', namespace='Pages')),
    path('product/', include('Products.urls', namespace='Product')),
    path('search/', include('Search.urls', namespace='Search')),
    path('search/ajax/', include('Search.ajax_urls', namespace='Ajax')),
    path("cart/", include("Cart.urls", namespace="Cart")),
    path("staff/", include("Staff.urls", namespace="Staff")),
    path("order/", include("Orders.urls", namespace="Orders")),
    path("payment/", include("Payments.urls", namespace="Payments")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
from django.db import models

# Create your models here.

Cart/forms.py
from django import forms
from django.conf import settings

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, settings.CART_ITEM_MAX_QUANTITY + 1)
]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        label="Quantity", choices=PRODUCT_QUANTITY_CHOICES, coerce=int
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

Cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from Products.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )

    return redirect("Cart:detail")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("Cart:detail")


def cart_detail(request):
    request.session["get_shipping_price"]={"shippmentCost":0}
    cart = Cart(request)
    return render(request, "cart/cart_detail.html", {"cart": cart})

templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %} {% if user.is_authenticated %} {{user.username}} {% else %} YRYRPars {% endif %} | Cart{% endblock title %}
{% block css %}
{% endblock css %}
{% block content %}
<div style="height:70px; width: 100vw;"></div>
<div class="container my-3 " >
    <h1 class="font-weight-bold" style="padding: 20px; text-align: center;" >My Cart</h1>
    {% if cart %}
    <table class="table">
        <thead>
            <tr class="bg-light">
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Product Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td class="align-middle">
                    <a target="_blank" class="text-decoration-none" href="{{ product.get_absolute_url }}">
                        <img style="width: 120px; height: 120px;" src="{{product.product_photo_url}}" alt="{{ product.product_name }}">
                        {{ product.product_name }}
                    </a>
                </td>
                <td class="align-middle">
                    <form action="{% url 'Cart:add' product.id %}" method="post" style="margin-block: 10px;">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col" style="margin-bottom: 10px;">
                                {% render_field item.update_quantity_form.quantity class+="form-control" %}
                            </div>
                            <div class="col">
                                <input class="btn btn-info" type="submit" value="Update">
                            </div>
                        </div>
                        {{ item.update_quantity_form.override }}
                    </form>
                    <form action="{% url 'Cart:remove' product.id %}" method="post">
                        <div class="form-row">
                            <div class="col">
                                {% csrf_token %}
                                <input class="btn btn-danger" type="submit" value="Remove" >
                            </div>
                        </div>
                    </form>
                </td>
                <td class="align-middle">${{ item.price }}</td>

            </tr>
            {% endwith %}
            {% endfor %}
            <tr class="bg-light">
                <td class="font-weight-bold">Total</td>
                <td></td>
                <td class="font-weight-bold">$ {{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    {% else %}
    <p>Your Cart Is Empty</p>
    {% endif %}
    <p class="text-right">
        <a class=" btn btn-primary" href="{% url 'Product:product_listview' %}">
            Keep Buying
        </a>

        <a  style="color: #fff;" {% if user.is_authenticated %}{% block login %} class="btn btn-success {% if not cart %}disabled{% endif %}" href="{% url 'Orders:create' %}"{% endblock login %}{% else %} class="btn btn-success" id="mustlogin"{% endif %} >
            Check Out
        </a>
    </p>
</div>

{% endblock content %}