Cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = "Cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

Products/urls.py
from django.urls import path, include
from .views import *


app_name = 'Product'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_listview'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detailview'),
    path('ajax/', include('Products.ajaxurls')),
    path('land/<str:vland>', ProductListByLand, name="land"),
]

Search/urls.py
from django.urls import path, include
from .views import *

app_name = 'Search'

urlpatterns = [
    path('searchbar/', SearchBar, name='searchbar'),
    path('filters/', Filters, name='filters'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login.urls', namespace='Account')),
    path('', include('StaticPages.urls', namespace='Pages')),
    path('product/', include('Products.urls', namespace='Product')),
    path('search/', include('Search.urls', namespace='Search')),
    path('search/ajax/', include('Search.ajax_urls', namespace='Ajax')),
    path("cart/", include("Cart.urls", namespace="Cart")),
    path("staff/", include("Staff.urls", namespace="Staff")),
    path("order/", include("Orders.urls", namespace="Orders")),
    path("payment/", include("Payments.urls", namespace="Payments")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Search/models.py
from django.db import models

# Create your models here.

Search/views.py
from django.shortcuts import render, redirect
from Products.models import Product, Find_a_Part
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


def SearchBar(request):
    if request.method=="POST":
            product_OEM = request.POST.get('searched')
            filter_oem_middleware = Product.objects.filter(product_OEM__contains = product_OEM)
            page = request.GET.get('page', 1)
            paginator = Paginator(filter_oem_middleware, 12)
            try:
                filter_oem = paginator.page(page)
            except PageNotAnInteger:
                filter_oem = paginator.page(1)
            except EmptyPage:
                filter_oem = paginator.page(paginator.num_pages)
            return render(request, 'search/OEM.html', {'product':filter_oem, 'term':request.POST.get('searched')})

def Filters(request):
    if request.method == 'POST':
        if request.POST.get('subcategory') and request.POST.get("brand"):
            filters_category = Find_a_Part.objects.filter(vehicle_type = request.POST.get('Vtype'),
                                                    make = request.POST.get('Make'), 
                                                    model = request.POST.get('Model'), 
                                                    year__contains = request.POST.get('Year'),
                                                    category = request.POST.get("category"),
                                                    sub_category = request.POST.get('subcategory'),
                                                    brand = request.POST.get("brand"))
        elif request.POST.get('subcategory'):
            filters_category = Find_a_Part.objects.filter(vehicle_type = request.POST.get('Vtype'),
                                                    make = request.POST.get('Make'), 
                                                    model = request.POST.get('Model'), 
                                                    year__contains = request.POST.get('Year'),
                                                    category = request.POST.get("category"),
                                                    sub_category = request.POST.get('subcategory'))
        else:
            filters_category = Find_a_Part.objects.filter(vehicle_type = request.POST.get('Vtype'),
                                                    make = request.POST.get('Make'), 
                                                    model = request.POST.get('Model'), 
                                                    year__contains = request.POST.get('Year'),
                                                    category = request.POST.get("category"))
        product_filter =  Product.objects.filter(product_find_part = filters_category.values('id')[0]['id'])
        return render(request, 'search/filters.html', {'product':product_filter})
    return render(request, 'search/filters.html')

templates/search/OEM.html
{% extends 'base.html' %}
{% block title %}Results | {{term}}{% endblock title %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/product_list.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"> 
{% endblock css %}

{% block content %}
<div class="product-header">
    <img src="{% static 'img/vehicle-parts.jpg' %}" alt='Resultes for "{{term}}"'>
    <h1>Results for "{{term}}"</h1>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path fill="#F2F2F2" fill-opacity="1" d="M0,224L1440,128L1440,320L0,320Z"></path>
    </svg>
</div>
<div id="scroll_to" class="section-featured">
{% if product %}
{% include "products.html" with product=product %}
{% else %}
<h1 style="text-align:center; font-size:3rem; color:;">"No Results"</h1>
{% endif %}
</div>
<div class="paginator_land">
{% if product.has_other_pages %}
  <ul class="pagination">
    {% if product.has_previous %}
      <li><a href="?page={{ product.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in product.paginator.page_range %}
      {% if product.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if product.has_next %}
      <li><a href="?page={{ product.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
{% endblock content%}

{% block script %}
<script src="{% static 'js/scroll.js' %}"></script>
{% endblock script %}

templates/search/filters.html
{% extends 'base.html' %}
{% block title %}YRYR Parts | Home{% endblock title %} 
{% load static %} 
{% block css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/filters.css' %}"> 
{% endblock css %} 
{% block content %}
<div style="width: 100vw; height: 80px;"></div>
<div class="find-a-part-containder">
    <div class="center_flex">
        <div class="img_box"></div>
    <div class="title_find">
        <h1>Find a</h1>
        <h1 class="title_giga">Part</h1>
    </div>
    <div class="sub-title-index">
        Use Our Tool To Find The Best Deal <br>On 
            The Part You Need For Your Powersport Vehicle
    </div>

    <div class="form-filter">
    <form method="post" action="{% url 'Search:filters' %}">
        <div class='selects'>
            {% csrf_token %}
            <div class="box-form">
                <p for="Vtype">Vehicle Type<span style="color: red;">*</span></p>
                <select name="Vtype" id="Vtype" data-vehicle_type-url="{% url 'Ajax:vehicle_type' %}" required></select>
                <p for="Make">Make<span style="color: red;">*</span></p>
                <select name="Make" id="Make" data-make-url="{% url 'Ajax:make' %}" required>
                        <option value="">---------</option>
                    </select>
                <p for="Model">Model<span style="color: red;">*</span></p>
                <select name="Model" id="Model" data-model-url="{% url 'Ajax:model' %}" required>
                        <option value="">---------</option>
                    </select>
            </div>
            <div class="box-form">
                <p for="Year">Year<span style="color: red;">*</span></p>
                <select name="Year" id="Year" data-year-url="{% url 'Ajax:year' %}" required>
                        <option value="">---------</option>
                    </select>
                <p for="category">Category<span style="color: red;">*</span></p>
                <select name="category" id="category" data-category-url="{% url 'Ajax:category' %}"  required>
                        <option value="">---------</option>
                    </select>
                <p for="subcategory">Sub Category</p>
                <select name="subcategory" id="subcategory" data-subcategory-url="{% url 'Ajax:subcategory' %}">
                        <option value="">---------</option>
                    </select>
                <p for="brand">Brand</p>
                <select name="brand" id="brand" data-brand-url="{% url 'Ajax:brand' %}">
                        <option value="">---------</option>
                    </select>
            </div>
        </div>
        <div class="btn-filter">
            </br>
            <button class="btn-submit-form"type="submit">Find My Part <i class="fas fa-search"></i></button>
        </div>
    </form>
</div>
</div>
</div>
<div id="scroll_to" style="width:100%; background:#69BD28; height:40px;"></div>
{% if product %}
{% else %}
<div class="find-a-part-container-vtype">
    <a href="{% url 'Product:land' 'Ground' %}"><img class="vtype-img" src="{% static 'img/4road.png' %}"></a>
    <a href="{% url 'Product:land' 'Water' %}"><img class="vtype-img" src="{% static 'img/jetski.png' %}"></a>
    <a href="{% url 'Product:land' 'Snow' %}"><img class="vtype-img"src="{% static 'img/snowmobile.png' %}"></a>
</div>
{% endif %}
</div>
{% if product %} {% block products %}
<div style="padding:30px 0;"class="section-featured">
<div class="products-carrousel">
    <div class="page-wrapper">
        <div class="page-inner">
            <div class="row">
                {% for i in product %}
                {% if i.is_active %}
                {% block product_validation %}
                <div style=" width:500px; box-shadow:0 0px 5px 5px #69BD28;" class="el-wrapper">
                    <div class="box-up">
                        <img class="img" src="{{i.product_photo_url}}" alt="{{i.product_name}}">
                        <div class="img-info">
                            <div class="info-inner">
                                <span class="p-name"  style="font-family:'roboto'; font-size: 1.3rem; margin-bottom: 15px;">{{i.product_name}}</span>
                            </div>
                            <div class="a-size">
                            <ul style="list-style: none;">
                                <li>{{i.get_category_vehicle_type}}</li>
                                <li>{{i.get_category_sub_category}}</li>
                            </ul>
                            </div>
                        </div>
                    </div>
                    <div class="box-down">
                        <div class="h-bg">
                            <div class="h-bg-inner"></div>
                        </div>
                        {% if i.product_stock == 0 %}
                        {% block outstock %}
                        <a class="cart">
                            {% if i.product_sale_price %}
                            <span class="price" style="font-size:1.1rem;">${{i.product_sale_price}}</span>
                            {% else %}
                            <span class="price" style="font-size:1.1rem;">${{i.product_price}}</span>
                            {% endif %}
                            <span class="add-to-cart">
                                    <span class="txt">Product Out Of Stock</span>
                            </span>
                        </a>
                        {% endblock outstock %}
                        {% else %}
                        {% block stock %}
                        <a class="cart" href="{{i.get_absolute_url}}">
                            {% if i.product_sale_price %}
                            <span style="font-size:1.1rem;" class="price">${{i.product_sale_price}}</span>
                            {% else %}
                            <span style="font-size:1.1rem;" class="price">${{i.product_price}}</span>
                            {% endif %}
                            <span class="add-to-cart">
                                    <span class="txt">View Product</span>
                            </span>
                        </a>
                        {% endblock stock %}
                        {% endif %}
                    </div>
                </div>
                {% endblock product_validation %}
                {% endif %}
                {% endfor %}         
            </div>
        </div>
    </div>
</div>


</div>
{% endblock products %} {% endif %} {% endblock content %} {% block script %}
<script src="{% static 'js/filters.ajax.js' %}"></script>
<script src="{% static 'js/scroll.js' %}"></script>
{% endblock script %}