Cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = "Cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

Login/urls.py
from django.urls import path
from .views import *

app_name='Account'

urlpatterns = [
    path('login/', loginPage, name="login"),
    path('logout/', logoutPage, name="logout"),
    path('register/', registrationPage, name="register"),
]

Products/urls.py
from django.urls import path, include
from .views import *


app_name = 'Product'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_listview'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detailview'),
    path('ajax/', include('Products.ajaxurls')),
    path('land/<str:vland>', ProductListByLand, name="land"),
]

Search/urls.py
from django.urls import path, include
from .views import *

app_name = 'Search'

urlpatterns = [
    path('searchbar/', SearchBar, name='searchbar'),
    path('filters/', Filters, name='filters'),
]

Staff/urls.py
from django.urls import path
from .views import *
app_name='Staff'

urlpatterns = [
    path('', ExcelView, name='excel')
]

StaticPages/urls.py
from django.urls import path
from .views import *

app_name='Pages'

urlpatterns = [
    path('', Home, name='home'),
    path('contact/', ContactUs, name='contact'),
    path('about/', About, name='about'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login.urls', namespace='Account')),
    path('', include('StaticPages.urls', namespace='Pages')),
    path('product/', include('Products.urls', namespace='Product')),
    path('search/', include('Search.urls', namespace='Search')),
    path('search/ajax/', include('Search.ajax_urls', namespace='Ajax')),
    path("cart/", include("Cart.urls", namespace="Cart")),
    path("staff/", include("Staff.urls", namespace="Staff")),
    path("order/", include("Orders.urls", namespace="Orders")),
    path("payment/", include("Payments.urls", namespace="Payments")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from autoslug import AutoSlugField
from django.urls import reverse

class Category(models.Model):
    vehicle_land                = models.CharField(max_length=50)
    vehicle_type                = models.CharField(max_length=50)
    category                    = models.CharField(max_length=50, blank=True, null=True)
    sub_category                = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        return self.sub_category
    
    class Meta:
        db_table = 'categories'

class Find_a_Part(models.Model):
    vehicle_type                = models.CharField(max_length=250)
    make                        = models.CharField(max_length=250, blank=True, null=True)
    model                       = models.CharField(max_length=250, blank=True, null=True)  
    year                        = models.CharField(max_length=250, blank=True, null=True)
    brand                       = models.CharField(max_length=250, blank=True, null=True)  
    category                    = models.CharField(max_length=250, blank=True, null=True)  
    sub_category                = models.CharField(max_length=250, blank=True, null=True) 
    


class Product(models.Model):
    product_name                = models.CharField(max_length=250)
    product_SKU                 = models.CharField(max_length=250, unique=True)
    product_OEM                 = models.CharField(max_length=250, blank=True, null=True)
    product_is_OEM              = models.BooleanField(default=False)
    product_photo_url           = models.URLField() 
    product_price               = models.DecimalField(max_digits=15, decimal_places=2)
    product_sale_price          = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    product_short_description   = models.TextField(max_length=150, blank=True, null=True)
    product_description         = models.TextField()
    product_add_date            = models.DateField(auto_now_add=True)
    product_width               = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
    product_height              = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
    product_lenght              = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
    product_weight              = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
    slug                        = AutoSlugField(unique=True, always_update=False, populate_from="product_name")
    is_active                   = models.BooleanField(default=True)
    product_stock               = models.IntegerField(blank=True, null=True)
    product_category            = models.ForeignKey(Category, on_delete=CASCADE)
    product_find_part           = models.ManyToManyField(Find_a_Part) 

    def __str__(self):
        return self.product_name
    

    def get_absolute_url(self):
        return reverse("Product:product_detailview", kwargs={"slug": self.slug})

    def get_category_vehicle_land(self):
        category = self.product_category.vehicle_land
        return category
    
    def get_category_vehicle_type(self):
        category = self.product_category.vehicle_type
        return category
    
    def get_category_category(self):
        category = self.product_category.category
        return category
    
    def get_category_sub_category(self):
        category = self.product_category.sub_category
        return category
    
    class Meta:
        db_table = 'products'




    

Products/forms.py
from Products.models import ShippingAddress
from django.forms import ModelForm, fields
from .models import ShippingAddress

class ShippingAddressForm(ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ['address_1','address_2','city','state','zip_code']

Products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import *
from Cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

class ProductListView(ListView):
    paginate_by = 12
    def get_queryset(self):
        queryset = Product.objects.filter(is_active = True)
        return queryset

class ProductDetailView(DetailView):
    queryset = Product.objects.filter(is_active=True)
    extra_context = {"form": CartAddProductForm()}

def ProductListByLand(request, vland):
    queryset_middleware = Product.objects.filter(product_category__vehicle_land__contains = vland)
    page = request.GET.get('page', 1)
    paginator = Paginator(queryset_middleware, 12)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    return render(request, 'search/OEM.html', {'product':queryset, 'term': vland})

templates/base.html
 {% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/product_card.css' %}">
    <link rel="stylesheet" href="{% static 'css/login_modal.css' %}">
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">  {% block css %}{% endblock css %}
</head>

<body>
    <div class="awesome_wrapper">
        <nav>
            <input type="checkbox" id="show-search">
            <input type="checkbox" id="show-menu">
            <label for="show-menu" class="menu-icon"><i class="fas fa-bars"></i></label>
            <div class="content">
                <div class="logo">
                    <a href="{% url 'Pages:home' %}"><img src="{% static 'img/logo.png' %}"></a>
                </div>
                <ul class="links">
                    <li><a href="{% url 'Pages:home' %}">Home</a></li>
                    <li><a href="{% url 'Pages:about' %}">About</a></li>
                    <li><a href="{% url 'Pages:contact' %}">Contact Us</a></li>
                    <!--li>
                        <a href="#" class="desktop-link">Features</a>
                        <input type="checkbox" id="show-features">
                        <label for="show-features">Features</label>
                        <ul>
                            <li><a href="{% url 'Search:filters' %}">Find A Part</a></li>
                        </ul>
                    </li-->
                    <li><a href="{% url 'Product:product_listview' %}">Products</a></li>
                    <!--li>
                        <a href="{% url 'Product:product_listview' %}" class="desktop-link">Products</a>
                        <input type="checkbox" id="show-services">
                        <label for="show-services">Products</label>
                        <ul>
                            
                            <li>
                                <a href="#" class="desktop-link">More Items</a>
                                <input type="checkbox" id="show-items">
                                <label for="show-items">More Items</label>
                                <ul>
                                    <li><a href="#">Sub Menu 1</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li-->
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'Account:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a id="login">Login</a></li>
                    <li><a href="{% url 'Account:register' %}">Register</a></li>
                    {% endif %}
                    {% if user.is_staff %}
                    <li><a href="{% url 'Staff:excel' %}">Add Product</a></li>
                    {% endif %}
                    <li><a style="font-size: 1.3rem; color: #2D2570; padding: 30px 17px;" href="{% url 'Cart:detail' %}"><i class="fas fa-shopping-cart"></i></a></li>
                    
                </ul>
            </div>
            <label for="show-search" class="search-icon"><i class="fas fa-search"></i></label>
            <form action="{% url 'Search:searchbar' %}" class="search-box" method='post'>
                {% csrf_token %}
                <input name="searched" type="text" placeholder="Search By OEM" required>
                <button type="submit" class="go-icon"><i class="fas fa-long-arrow-alt-right"></i></button>
            </form>
        </nav>
    </div>


    <div class="main-container">
        {% block content %} {% endblock content %}
    </div>
    <div class="footer">
        <div class="box-footer">
            <h3>Features</h3>
            <h4>Find a Part</h4>
            <h4> How to Videos</h4>
        </div>
        <div class="box-footer">
            <h3>Vehicles</h3>
            <h4>Jet Ski</h4>
            <h4>Jet Boat</h4>
            <h4>ATV / UTV</h4>
            <h4>Snowmobile</h4>
        </div>
        <div class="box-footer">
            <h3>About</h3>
            <a href="https://www.ebay.com/usr/h2oandsnow1">
                <h4>eBay Store</h4>
            </a>
            <h4>Community</h4>
            <h4>Our Story</h4>
        </div>
        <div class="box-footer">
            <h3>Contact</h3>
            <h4>727 648 4823</h4>
            <h4>YRYR.Parts@gmail.com</h4>
            <a href="https://www.google.com/maps/place/624+E+Bay+Dr+%235,+Largo,+FL+33770/@27.9168341,-82.7825105,17z/data=!3m1!4b1!4m5!3m4!1s0x88c2fa7dd3bbfad3:0x232297250157e077!8m2!3d27.9168341!4d-82.7803218">
                <h4>Map</h4>
            </a>
        </div>
    </div>
    <div class="social-footer">
        <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
        <a href="https://www.facebook.com/yourrealmyourride/" target="_blank"><i class="fab fa-facebook-f"></i></a>
        <a href="#" target="_blank"><i class="fab fa-youtube"></i></a>
        <a href="https://www.instagram.com/yourrealmyourride/?hl=en" target="_blank"><i class="fab fa-instagram"></i></a>
    </div>
    <div class="footer-footer">
        <p>YRYRParts © 2021</p>
    </div>
    
    <div class="login_modal">
        <form action="{% url 'Account:login' %}" method="post">
        {% csrf_token %}
            <input type="hidden" name="path" value="{{request.path}}">
            <i id="close_modal"class="fas fa-times"></i>
            <h2>Login</h2>
            <p>E-mail:</p>
            <input type="email" name="email" required>
            <p>Password:</p>
            <input type="password" name="password"></br>
            <input class="btn_login_submit" type="submit" value="Login" required>
            <p><a href="{% url 'Account:register' %}" style="text-align: center; color: #69BD28; text-decocation: none;">Create An Account</a></p>
        </form>
    </div>
    <script>
        var giftofspeed = document.createElement('link');
    giftofspeed.rel = 'stylesheet';
    giftofspeed.href = "{% static 'css/font_awesome.css' %}";
    giftofspeed.type = 'text/css';
    var godefer = document.getElementsByTagName('link')[0];
    godefer.parentNode.insertBefore(giftofspeed, godefer);

    </script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/loginpopup.js' %}"></script>
   
{% block script %}{% endblock script %}


</body>

templates/order_summary.html
<div class="card border-0 bg-light p-4">
    <h4>Order Summary</h4>
    <ul class="list-group list-group-flush">
        {% if service_name %}
        <div style="width: 100%;">{{shipping_price}}- Cost:$ {{total_price}}</div>
        {% endif %}
        {% for item in items %}
        <li style="font-family: 'roboto' !important; display: flex;" class="list-group-item bg-light">
            <img style="width: 100px; height: 100px;"src="{{item.product.product_photo_url}}">
            <div style="width: 250px;">
            <p style="font-family: 'roboto' !important;">
            {{ item.quantity }}x {{ item.product.product_name }}
            <span class="float-right"> $ {{ item.total_price }}{{ item.get_total_price }} </span>
            </p>
            </div>
        </li>
        {% endfor %}
        {% if total_price %}
        <li style="font-family: 'roboto' !important;" class="font-weight-bold list-group-item bg-light">Total:
            <span style="font-family: 'roboto' !important;" class="float-right"> $ {{ total_price }}</span>
        </li>
        {% endif %}
    </ul>
</div>

templates/pagination.html
<div class="pagination">
    <p>{% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    Page {{ page.number }} Of {{ page.paginator.num_pages }}.
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}</p>
</div>

templates/products.html
<div class="products-carrousel">
    <div class="page-wrapper">
        <div class="page-inner">
            <div class="row">
                {% for i in product %}
                {% if i.is_active %}
                {% block product_validation %}
                <div class="el-wrapper">
                    <div class="box-up">
                        <img class="img" src="{{i.product_photo_url}}" alt="{{i.product_name}}">
                        <div class="img-info">
                            <div class="info-inner">
                                <span class="p-name"  >{{i.product_name}}</span>
                            </div>
                            <div class="a-size">
                            <ul style="list-style: none;">
                                <li>{{i.get_category_vehicle_type}}</li>
                                <li>{{i.get_category_sub_category}}</li>
                            </ul>
                            </div>
                        </div>
                    </div>
                    <div class="box-down">
                        <div class="h-bg">
                            <div class="h-bg-inner"></div>
                        </div>
                        {% if i.product_stock == 0 %}
                        {% block outstock %}
                        <a class="cart">
                            {% if i.product_sale_price %}
                            <span class="price" style="font-size:1.1rem;">${{i.product_sale_price}}</span>
                            {% else %}
                            <span class="price" style="font-size:1.1rem;">${{i.product_price}}</span>
                            {% endif %}
                            <span class="add-to-cart">
                                    <span class="txt">Product Out Of Stock</span>
                            </span>
                        </a>
                        {% endblock outstock %}
                        {% else %}
                        {% block stock %}
                        <a class="cart" href="{{i.get_absolute_url}}">
                            {% if i.product_sale_price %}
                            <span style="font-size:1.1rem;" class="price">${{i.product_sale_price}}</span>
                            {% else %}
                            <span style="font-size:1.1rem;" class="price">${{i.product_price}}</span>
                            {% endif %}
                            <span class="add-to-cart">
                                    <span class="txt">View Product</span>
                            </span>
                        </a>
                        {% endblock stock %}
                        {% endif %}
                    </div>
                </div>
                {% endblock product_validation %}
                {% endif %}
                {% endfor %}         
            </div>
        </div>
    </div>
</div>