Cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = "Cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

Orders/urls.py
from django.urls import path
from .views import *

app_name = "Orders"

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="create"),
    path("GetRates/", GetShippingRates, name="GetRates"),
    path("Update_price/", UpdateTotalPrice, name="update_price")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login.urls', namespace='Account')),
    path('', include('StaticPages.urls', namespace='Pages')),
    path('product/', include('Products.urls', namespace='Product')),
    path('search/', include('Search.urls', namespace='Search')),
    path('search/ajax/', include('Search.ajax_urls', namespace='Ajax')),
    path("cart/", include("Cart.urls", namespace="Cart")),
    path("staff/", include("Staff.urls", namespace="Staff")),
    path("order/", include("Orders.urls", namespace="Orders")),
    path("payment/", include("Payments.urls", namespace="Payments")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Orders/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from model_utils.models import TimeStampedModel
from localflavor.us.models import USStateField, USZipCodeField
from django.utils.translation import ugettext as _
from Login.models import AccountBase
from Products.models import Product


class Order(TimeStampedModel):
    address_1           = models.CharField("address 1", max_length=128)
    address_2           = models.CharField("address 2", max_length=128, blank=True)
    city                = models.CharField("city", max_length=64, default="Zanesville")
    state               = USStateField("state", default="OH")
    zip_code            = USZipCodeField("zip code", default="43701")
    user                = models.ForeignKey(AccountBase, on_delete=models.DO_NOTHING)
    is_paid             = models.BooleanField(default=False)
    is_complete         = models.BooleanField(default=False)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Order {self.id}"

    def get_total_price(self):
        total_cost = sum(item.get_total_price() for item in self.items.all())
        return total_cost

    def get_description(self):
        return ", ".join(
            [f"{item.quantity}x {item.product.name}" for item in self.items.all()]
        )


class Item(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(settings.CART_ITEM_MAX_QUANTITY),
        ]
    )

    def __str__(self):
        return str(self.id)

    def get_total_price(self):
        return self.price * self.quantity

Orders/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Fieldset, Layout, Submit
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "address_1",
            "address_2",
            "city",
            "state",
            "zip_code",
            "user"
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_action = "."
        self.helper.add_input(
            Submit(
                "submit",
                "Checkout",
                css_class="btn btn-success btn-lg btn-block",
            )
        )
        self.helper.layout = Layout(
            Fieldset(
                "",
                Div(
                    Field("zip_code", wrapper_class="col"),
                    Field("state", wrapper_class="col"),
                    Field("city", wrapper_class="col"),
                    css_class="row",
                ),
                Div(
                    Field("address_1", wrapper_class="col"),
                    Field("address_2", wrapper_class="col"),
                    Field("user", wrapper_class="col"),
                    css_class="row",
                ),
                css_class="border-bottom mb-3",
            )
        )

Orders/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView
from Cart.cart import Cart
from django.http import JsonResponse
from .forms import OrderCreateForm
from .models import Item, Order
from core.settings import SHIPPING_API_Key as apikey, SHIPPING_API_Secret as apisecret
import requests
import json
from decimal import Decimal


def Data_processor_json(lists):
    final_return = []
    for carrier in lists:
        if carrier:

            for quote in carrier:
                total = quote["otherCost"] + quote["shipmentCost"]
                quote["totalPrice"] = total
            sorted(carrier, key = lambda i: i['totalPrice'])
            final_return.append(carrier[-1])
    return final_return

class OrderCreateView(CreateView):
    model = Order
    form_class = OrderCreateForm

    def form_valid(self, form):
        cart = Cart(self.request)
        if cart:
            order = form.save()
            for item in cart:
                Item.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )
            self.request.session["order_id"] = order.id
            return redirect(reverse("Payment:checkout"))
        return redirect(reverse("Pages:home"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cart"] = Cart(self.request)
        return context
    
def GetShippingRates(request):
    cart = Cart(request)
    weight = 0

    for item in cart:
        weight = weight + item["product"].product_weight
    
    data_Zipcode = request.GET.get("data-Zipcode")
    data_State = request.GET.get("data-State")
    data_City = request.GET.get("data-City")
    data_Address_1 = request.GET.get("data_Address_1")
    data_Address_2 = request.GET.get("data_Address_2")
    headers = {"content-type": "application/json"}
    
    data_Carrier = [{"serviceName":"fedex", "serviceCode":"fedex_home_delivery"},
    {"serviceName":"fedex", "serviceCode":"fedex_ground"},
    {"serviceName":"stamps_com", "serviceCode":"usps_priority_mail"}]

    list_service = []
    for item in data_Carrier:
        if request.GET.get("data-Zipcode") and request.GET.get("data-City") and request.GET.get("data_Address_1"):
            data = {
                "carrierCode": item["serviceName"],
                "serviceCode": item["serviceCode"],
                "packageCode": None,
                "fromPostalCode": "33770",
                "toState": data_State,
                "toCountry": "US",
                "toPostalCode": data_Zipcode,
                "toCity": data_City,
                "weight": {
                  "value": str(weight),
                  "units": "pounds"
                },
                "confirmation": "delivery",
                "residential": True
            }
            r = requests.post('http://ssapi.shipstation.com/shipments/getrates', auth=(apikey, apisecret), data=json.dumps(data), headers=headers)
            if json.loads(r.text) not in list_service:
                list_service.append(json.loads(r.text))
        else:
            return JsonResponse({"error_service":"Error, Check your Address!"}, safe=False)
    
    if cart.get_total_price() >= 150:
        new_list = [{"totalPrice":0, "serviceName":"Free Shipping", "serviceCode":"free"}]
    else:
        new_list = Data_processor_json(list_service)
    
    shipment_context = {"data_Zipcode": data_Zipcode, "data_State": data_State, "data_City": data_City, "data_Address_1": data_Address_1, "data_Address_2": data_Address_2}
    request.session["shipment_context"] = shipment_context
    return JsonResponse(new_list, safe=False)

def UpdateTotalPrice(request):
    data_Service_code = request.GET.get("data_Price")
    data_Coust = request.GET.get("data_Service")
    shippment_service = {"serviceName": data_Service_code, "shippmentCost": data_Coust,}
    request.session["get_shipping_price"] = shippment_service
    return JsonResponse({"checked":'<i style="font-size:6rem; text-align:center; color:rgb(105, 189, 40);" class="fas fa-check"></i>'}, safe=False)

       

templates/Orders/order_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}Checkout{% endblock title %}
{% block css %}
<style>
#div_id_user{
    display: none;
}
@-webkit-keyframes rotating /* Safari and Chrome */ {
  from {
    -webkit-transform: rotate(0deg);
    -o-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  to {
    -webkit-transform: rotate(360deg);
    -o-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@keyframes rotating {
  from {
    -ms-transform: rotate(0deg);
    -moz-transform: rotate(0deg);
    -webkit-transform: rotate(0deg);
    -o-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  to {
    -ms-transform: rotate(360deg);
    -moz-transform: rotate(360deg);
    -webkit-transform: rotate(360deg);
    -o-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
.dimmer{
    display: grid;
    place-items: center;
    position: fixed;
    top:0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,.5);
    color: white;
    z-index: 99999;
}
.rotating {
    font-size: 5rem;
  -webkit-animation: rotating 2s linear infinite;
  -moz-animation: rotating 2s linear infinite;
  -ms-animation: rotating 2s linear infinite;
  -o-animation: rotating 2s linear infinite;
  animation: rotating 2s linear infinite;
}
</style>
{% endblock css %}
{% block content %}
<div style="width: 100vw; height: 80px;"></div>
<div class="container my-3">
    <h1 class="font-weight-bold">Checkout</h1>
    <div class="summary_order" style="padding:20px 0;">
        {% include "order_summary.html" with items=cart total_price=cart.get_total_price %}
    </div>
    {% if cart %}
    <div class="row">
        <div class="col-lg-6">
            <h1>Shipping Options</h1>
            <div class="shipping" style="display: flex; align-items: center;">
                <div id="carrier" url-data="{% url 'Orders:GetRates' %}" url-data-update="{% url 'Orders:update_price' %}">
                    <div style="margin: 40px 0; cursor: pointer;" id="shippingOptions" url-data="{% url 'Orders:GetRates' %}" onclick="selectshipping()" class="btn btn-primary btn btn-success btn-lg btn-block">Calculate Shipping Cost</div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            {% crispy form %}
        </div>
    </div>
    {% else %}
    <p>Your Cart Is Empty.</p>
    {% endif %}
</div>

{% endblock content %}

{% block script %}
<script>
    $(document).ready(function() {
    $("#submit-id-submit").attr("disabled", true);
    let userID = "{{user.id}}";
    let userUsername = "{{user.username}}";
    $('#id_user').html(`<option value="${userID}" selected>${userUsername}</option>`);
    })
</script>
<script>
function selectshipping(){
    let zip_code = $("#id_zip_code").val(),
        state = $("#id_state").val(),
        city = $("#id_city").val(),
        address1 = $("#id_address_1").val(),
        address2 = $("#id_address_2").val();
    let uri = $("#carrier").attr("url-data");
    if (address1==false|| state==false || city==false || zip_code==false  ){

        window.alert("Please fill out all of the required options.");
        
    }else{
     
    
    $("#carrier").html("<div class='dimmer'><i class='fas fa-redo-alt rotating'/></div>");
    $.ajax({
        url: uri,
        data: {
            "data-Zipcode": zip_code,
            "data-State": state,
            "data-City": city,
            "data_Address_1": address1,
            "data_Address_2": address2
        },
        success: function(a) {
            $("#carrier").html(a);
            let t = '';
            a.forEach(function(a) {
                t += `<div onclick="updateTotalprice('${a.totalPrice}','${a.serviceCode}')" style="padding:10px; cursor:pointer; display:flex; align-items:center; gap:0 10px; text-decoration: underline; color:#002244; font-weight:600;"><input disabled type="checkbox" class="shippingOption" id="${a.serviceCode}"><div>${a.serviceName} Cost:${a.totalPrice}</div></div>`
            }), $("#carrier").html(t)
        }
    })
}
}

function updateTotalprice(total_price, service_code){
    let uri = $("#carrier").attr("url-data-update");
    $("input.shippingOption").removeAttr("checked");
    $("#"+service_code).attr("checked", true);
    $.ajax({
        url: uri,
        data: {
            "data-Price": total_price,
            "data-Service": service_code,
        },
        success: function(a) {
            let t = `${a.checked}`;
            $("#submit-id-submit").attr("disabled", false);
        }
    })
}
</script>
{% endblock script %}